FROM python:3.11-slim

# ARG DEVPI_HASEK_DEV_URL
# ENV PIP_INDEX_URL=$DEVPI_HASEK_DEV_URL \
#     PIP_EXTRA_INDEX_URL=https://pypi.org/simple

RUN --mount=type=secret,id=env \
    set -o allexport && \
    . /run/secrets/env && \
    set +o allexport && \
    pip install --upgrade --no-cache-dir \
      --index-url "$DEVPI_HASEK_DEV_URL" \
      --extra-index-url https://pypi.org/simple \
      stellar-harvest-ie-ui

ARG UI_PORT=8000
ENV UI_PORT=${UI_PORT}

# RUN pip install --upgrade --no-cache-dir \
#     stellar-harvest-ie-ui

WORKDIR /usr/local/lib/python3.11/site-packages

EXPOSE ${UI_PORT}

CMD ["uvicorn", "stellar_harvest_ie_ui", "--host", "0.0.0.0", "--port", "${UI_PORT}"]

# CMD uvicorn stellar_harvest_ie_ui.main:app \
#     --host 0.0.0.0 \
#     --port ${UI_PORT}