FROM python:3.11-slim

RUN --mount=type=secret,id=env \
    set -o allexport && \
    . /run/secrets/env && \
    set +o allexport && \
    pip install --upgrade --no-cache-dir \
      --index-url https://pypi.org/simple \
      --extra-index-url "$DEVPI_HASEK_DEV_URL" \
      --trusted-host host.docker.internal \
      stellar-harvest-ie-ui
    # Hosted on VPS - remove '--trusted-host'

ARG UI_PORT=8000
ENV UI_PORT=${UI_PORT}

# WORKDIR /usr/local/lib/python3.11/site-packages

EXPOSE ${UI_PORT}

CMD uvicorn stellar_harvest_ie_ui --host 0.0.0.0 --port $UI_PORT